---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
platforms:
  - name: "docker_ce-${image:-fedora}-${tag:-latest}${TOX_ENVNAME}"
    #image: "${namespace:-robertdebock}/${image:-fedora}:${tag:-latest}"
    image: "${image:-fedora}:${tag:-latest}"
    #command: /sbin/init
    #volumes:
    #  - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes
lint: |
  yamllint molecule/default/converge.yml
  ansible-lint molecule/default/converge.yml
verifier:
  name: ansible
provisioner:
  name: ansible
  log: True
