---
- hosts: galaxyservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secrets.yml
  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['acl', 'bzip2', 'git', 'make', 'python3-pip', 'python3-psycopg2', 'tar', 'virtualenv']
    - name: Install docker pip package
      ansible.builtin.pip:
        name: ['docker', 'drmaa']
    - name: Set docker user
      block:
        - name: Set _docker_users CentOS
          set_fact:
            _docker_users: ['centos']
          when: ansible_distribution == 'CentOS'
        - name: Set _docker_users Ubuntu
          set_fact:
            _docker_users: ['ubuntu']
          when: ansible_distribution == 'Ubuntu'
        - name: Set _docker_users Debian
          set_fact:
            _docker_users: ['debian']
          when: ansible_distribution == 'Debian'
        - name: Set docker_users
          set_fact:
            docker_users: "{{ _docker_users }}"
  post_tasks:
    - name: Install slurm-drmaa
      package:
        name: slurm-drmaa1
    - name: Copy LFQ-Analyst interactive tool into Galaxy code
      copy:
        src: 'galaxy/tools/lfq-analyst.xml'
        dest: '{{ galaxy_server_dir }}/tools/interactive/interactivetool_lfqanalyst.xml'
        owner: galaxy
        group: galaxy

  roles:
    - galaxyproject.repos
    - galaxyproject.slurm
    - galaxyproject.postgresql
    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres
    - geerlingguy.pip
    - galaxyproject.galaxy
    - role: uchida.miniconda
      become: true
      become_user: "{{ galaxy_user.name }}"
    - geerlingguy.docker
    - galaxyproject.nginx
    # - galaxyproject.tiaas2
    - usegalaxy_eu.gie_proxy  # Requires cloudflare API token
