---
- hosts: dbservers
  become: true
  become_user: root
  pre_tasks:
    - name: Install Dependencies
      package:
        name: 'acl'
  roles:
    - galaxyproject.postgresql
    - role: galaxyproject.postgresql_objects
      become: true
      become_user: postgres

- hosts: galaxyservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['acl', 'bzip2', 'git', 'make', 'tar', 'python3-venv', 'python3-setuptools']
  post_tasks:
  #   - name: Install slurm-drmaa
  #     package:
  #       name: slurm-drmaa1
    - name: Copy .bash-aliases
      copy:
        src: config/.bash_aliases
        dest: /home/ubuntu/.bash_aliases
        owner: ubuntu
        group: ubuntu
    - name: Copy local interactive tools
      copy:
        src: galaxy/tools/interactivetool_ena_upload.xml
        dest: "{{ galaxy_server_dir }}/tools/interactive/interactivetool_ena_upload.xml"
  roles:
    - galaxyproject.galaxy
    - role: galaxyproject.miniconda
      become: true
      become_user: "{{ galaxy_user_name }}"
    - galaxyproject.nginx
    - geerlingguy.docker
    - usegalaxy_eu.gie_proxy
