---
- hosts: galaxyservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['acl', 'bzip2', 'git', 'make', 'python3-psycopg2', 'tar', 'virtualenv']
  post_tasks:
    - name: Install slurm-drmaa
      package:
        name: slurm-drmaa1
  roles:
    - galaxyproject.repos
    - galaxyproject.slurm
    - galaxyproject.postgresql
    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres
    - geerlingguy.pip
    - galaxyproject.galaxy
    - role: uchida.miniconda
      become: true
      become_user: "{{ galaxy_user.name }}"
    - galaxyproject.nginx
    - geerlingguy.docker
    - usegalaxy_eu.tiaas2
    # - usegalaxy_eu.gie_proxy  # Won't work without cloudflare API token
