---
- src: galaxyproject.galaxy
  version: 0.10.3
- src: galaxyproject.nginx
  version: 0.7.0
- src: galaxyproject.postgresql
  version: 1.0.3
- src: natefoo.postgresql_objects
  version: 1.1
- src: geerlingguy.pip
  version: 2.0.0
- src: uchida.miniconda
  version: 0.3.0
- src: usegalaxy_eu.certbot
  version: 0.1.5
- src: galaxyproject.repos
  version: 0.0.2
- src: galaxyproject.slurm
  version: 0.1.3
- src: geerlingguy.docker
  version: 2.6.0
- src: usegalaxy_eu.gie_proxy
  version: 0.0.2
- src: usegalaxy_eu.tiaas2
  version: 0.0.8
- name: galaxyproject.cvmfs
  version: 0.2.16
- name: usegalaxy_eu.rabbitmqserver
  version: 1.2.0
- src: galaxyproject.pulsar
  version: 1.0.8
