---
- hosts: galaxyservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['acl', 'bzip2', 'git', 'make', 'python3-psycopg2', 'tar', 'virtualenv']
  post_tasks:
    - name: Install slurm-drmaa
      package:
        name: slurm-drmaa1
    - name: Copy .bash-aliases
      copy:
        src: config/.bash_aliases
        dest: /home/ubuntu/.bash_aliases
        owner: ubuntu
        group: ubuntu
    - name: Copy local tools
      copy:
        src: galaxy/tools/interactivetool_ena_upload.xml
        dest: "{{ galaxy_server_dir }}/tools/interactive/interactivetool_ena_upload.xml"
  roles:
    - galaxyproject.repos
    - galaxyproject.slurm
    - galaxyproject.postgresql
    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres
    - geerlingguy.pip
    - galaxyproject.galaxy
    - role: uchida.miniconda
      become: true
      become_user: "{{ galaxy_user.name }}"
    - galaxyproject.nginx
    - geerlingguy.docker
    - usegalaxy_eu.gie_proxy
