---
- name: Set container detail if standalone setup
  set_fact:
    rabbitmq_container_volumes: "{{ rabbitmq_container_standalone_setup_details.volumes|default([], true) }}"
    rabbitmq_container_ports: "{{ rabbitmq_container_standalone_setup_details.ports|default([], true) }}"
    rabbitmq_container_env: "{{ rabbitmq_container_standalone_setup_details.env|default({}, true) }}"
  when: rabbitmq_setup == "standalone"

- name: Set container detail if cluster setup
  set_fact:
    rabbitmq_container_volumes: "{{ rabbitmq_container_cluster_setup_details.volumes|default([], true) }}"
    rabbitmq_container_ports: "{{ rabbitmq_container_cluster_setup_details.ports|default([], true) }}"
    rabbitmq_container_env: "{{ rabbitmq_container_cluster_setup_details.env|default({}, true) }}"
  when: rabbitmq_setup == "cluster"

- name: Start a rabbitmq container
  community.docker.docker_container:
    name: "{{ rabbitmq_container.name }}"
    hostname: "{{ rabbitmq_container.hostname }}"
    image: "{{ rabbitmq_container.image }}"
    state: started
    restart_policy: always
    volumes: "{{ rabbitmq_container_volumes }}"
    ports: "{{ rabbitmq_container_ports }}"
    env: "{{ rabbitmq_container_env }}"

- name: Pause for some seconds to give time to the container to come up
  pause:
    seconds: "{{ rabbitmq_container_pause }}"
  when: rabbitmq_container_pause > 0
